language: python
# Python version 
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r src/requirements.txt
# command to run tests
script:
  - python3 -m pytest --flake8
# disable notifications
notifications:
  email: false
