#!/bin/bash

# @Author: AnthonyKenny98
# @Date:   2019-11-10 15:42:49
# @Last Modified by:   AnthonyKenny98
# @Last Modified time: 2020-01-20 14:28:14

cd -- "$(dirname "$BASH_SOURCE")"

RUN_LOG="logs/run.out"

clear
export FLASK_APP=src/app.py
export FLASK_ENV=development
export FLASK_DEBUG=False
source venv/bin/activate


printf "
===============================================================================
|                                                                             |
|                                   VendPLUS                                  |
|                                   --------                                  |
|                                                                             |
|                                                                             |
|                                                                             |
|                Locally Based Web Application is currently running.          |
|                    The application should open automatically                |
|                            in your default web browser.                     |
|                                                                             |
|                If nothing happens after a few seconds, go to                |
|                             http://127.0.0.1:5000                           |
|                                                                             |
|                                                                             |
|           https://github.com/AnthonyKenny98/Vend_Inventory_Upload           |
|                                                                             |
|                                                                             |
|                                                                             |
|                                  MIT License                                |
|                        Copyright © Anthony Kenny 2020                       |
===============================================================================
"

sleep 2
open 'http://127.0.0.1:5000'
flask run --host=127.0.0.1 > $RUN_LOG 2>&1
